version: "2"
services:
  app:
    build:
      context: .
      dockerfile: tests/docker/php/7.2/Dockerfile
    command: ["/code/tests/schedule.sh"]
    volumes:
      - .:/code
      - ./tests/app/runtime/composer:/root/.composer
    links:
      - db
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: app
      POSTGRES_PASSWORD: 'password'

  db:
    image: postgres:9.6
    volumes:
    - ./tests/docker/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
